version: "3.0"
services:

  wow-3.3.5a:
    image: vulcan/wow:3.3.5a
    ports:
      - 3724:3724/tcp
      - 8085:8085/tcp
    volumes:
      - wow-3.3.5a-logs:/opt/wow/server/bin/logs
      - wow-3.3.5a-config:/opt/wow/conf
    networks:
      - frontend
      - backend
    #command: bash -c "sleep 10 && /opt/wow/server/bin/start_server.sh"

  wow-3.3.5a-sql:
    image: mysql:5.7
    ports:
      - 3356:3306/tcp
    volumes:
      - wow-sql-data-3.3.5a:/var/lib/mysql
    networks:
      - frontend
      - backend

volumes: 
  wow-3.3.5a-logs:
  wow-3.3.5a-config:
  wow-sql-data-3.3.5a:

networks:
  frontend:
  backend:
